// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentRoutingPoc.Persistence.DbContexts;

#nullable disable

namespace PaymentRoutingPoc.Persistence.Migrations.Write
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260309162123_RemoveReferenceDataFromWriteContext")]
    partial class RemoveReferenceDataFromWriteContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PaymentRoutingPoc.Persistence.Models.Write.Snapshot", b =>
                {
                    b.Property<string>("SnapshotId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventStreamId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId");

                    b.HasIndex("EventStreamId")
                        .HasDatabaseName("idx_snapshot_stream_id");

                    b.HasIndex("EventStreamId", "AggregateType")
                        .IsUnique()
                        .HasDatabaseName("idx_snapshot_stream_aggregate");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("PaymentRoutingPoc.Persistence.Models.Write.StoredEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventStreamId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("GlobalVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCommitted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("EventId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("idx_event_type");

                    b.HasIndex("GlobalVersion")
                        .IsUnique()
                        .HasDatabaseName("idx_global_version");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_idempotency_key");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("idx_recorded_at");

                    b.HasIndex("EventStreamId", "AggregateVersion")
                        .IsUnique()
                        .HasDatabaseName("idx_stream_id_version");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
