// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentRoutingPoc.Persistence.DbContexts;

#nullable disable

namespace PaymentRoutingPoc.Persistence.Migrations.Read
{
    [DbContext(typeof(ReadDbContext))]
    partial class ReadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PaymentRoutingPoc.Persistence.Models.Read.MerchantPaymentStatistic", b =>
                {
                    b.Property<string>("MerchantId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AverageTransactionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedPayments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastPaymentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuccessRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulPayments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalPaymentsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalVolumeProcessed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MerchantId");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("idx_merchant_statistic_id");

                    b.ToTable("MerchantPaymentStatistics");
                });

            modelBuilder.Entity("PaymentRoutingPoc.Persistence.Models.Read.PaymentEventLog", b =>
                {
                    b.Property<string>("EventLogId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("EventLogId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_event_log_occurred_at");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("idx_event_log_payment_id");

                    b.HasIndex("PaymentId", "OccurredAt")
                        .HasDatabaseName("idx_event_log_payment_occurred");

                    b.ToTable("PaymentEventLogs");
                });

            modelBuilder.Entity("PaymentRoutingPoc.Persistence.Models.Read.PaymentReadModel", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastEventType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentId");

                    b.HasIndex("Amount")
                        .HasDatabaseName("idx_payment_amount");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_payment_created_at");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("idx_payment_merchant_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_payment_status");

                    b.HasIndex("Currency", "Status")
                        .HasDatabaseName("idx_payment_currency_status");

                    b.ToTable("PaymentsReadModel");
                });

            modelBuilder.Entity("PaymentRoutingPoc.Persistence.Models.Write.ProjectionCheckpoint", b =>
                {
                    b.Property<string>("ProjectionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckpointTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastProcessedGlobalVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectionState")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ProjectionId");

                    b.ToTable("ProjectionCheckpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
